### ISSUE TITLE
Removed quotes via function perhaps undesireable?

### ISSUE THREAD

**Issue by fourstepper** [arouene/vim-ansible-vault#2]
Hi!

First off, thanks for this wonderful tool.

I have noticed this snippet in the code, which automatically removes any excessive characters from the ansible-vault-targetted value.

Even though this behaviour is nice as it provides correct output in the end, this doesn't have to be the case, in cases like wanting to encrypt a password which ends with a `'` sign

```
" Remove single quotes, double quotes, spaces, tabs

function! s:unquote(string)
	return trim(a:string, '	 "''')
endfunction
```

Is this up for a discussion? Perhaps it could be modified via a variable in the .vimrc

Thanks!

**Comment by arouene** [comment]
Sorry for the late response, I didn't saw I had an issue opened !

That's a valid point, I don't remember why I unquote the string in the first place, but as you mentioned, we could want a password that start or ends with a quote.

So I added an option, now you can use `let g:ansible_vault_no_unquote = 1` to avoid unquoting.

I'm closing the issue as I have added an option to disable the unquoting, but don't hesitate to comment or re-open the issue if you have any remark or problem.

**Comment by fourstepper** [comment]
Thanks for this :)
